--INSERTS

INSERT INTO perfil (nombre_perfil, descripcion_perfil, estado_perfil)
VALUES 
    ('Administrativo', 'Perfil encargado de la gestión administrativa de los servicios médicos.', 1),
    ('Médico', 'Perfil encargado de la atención y diagnóstico de los pacientes.', 1),
    ('Enfermero', 'Perfil encargado del cuidado y asistencia directa a los pacientes.', 1);

INSERT INTO establecimiento (descripcion_establecimiento, direccion_establecimiento, ciudad_establecimiento, provincia_establecimiento, estado_establecimiento)
VALUES 
    ('Médico Independiente', 'Calle Principal #123, Sector Centro', 'Quito', 'Pichincha', 1),
    ('Hospital Metropolitano', 'Av. Mariana de Jesús s/n y Nicollari', 'Quito', 'Pichincha', 1),
    ('Hospital Luis Vernaza', 'Calle Pedro Carbo y 9 de Octubre', 'Guayaquil', 'Guayas', 1),
    ('Hospital IESS Cuenca', 'Avenida 12 de Abril y Unidad Nacional', 'Cuenca', 'Azuay', 1),
    ('Clínica Pichincha', 'Av. 10 de Agosto y Naciones Unidas', 'Quito', 'Pichincha', 1);

	INSERT INTO especialidad (nombre_especialidad, descripcion_especialidad, categoria_especialidad, uuid_especialidad, estado_especialidad)
VALUES
('Alergología', 'Especialidad dedicada al diagnóstico y tratamiento de alergias.', 'Alergología', NEWID(), 1),
('Ambulancia', 'Especialidad enfocada en la atención médica de emergencia y transporte sanitario.', 'Servicios de Emergencia', NEWID(), 1),
('Andrología', 'Especialidad dedicada al estudio y tratamiento de enfermedades del aparato reproductor masculino.', 'Andrología', NEWID(), 1),
('Anestesiología', 'Especialidad que se ocupa de la administración de anestesia y manejo del dolor durante cirugías.', 'Anestesiología', NEWID(), 1),
('Angiología', 'Especialidad centrada en el estudio y tratamiento de las enfermedades vasculares.', 'Angiología', NEWID(), 1),
('Audiología', 'Especialidad dedicada al estudio y tratamiento de los trastornos auditivos.', 'Audiología', NEWID(), 1),
('Banco de Sangre', 'Especialidad que se encarga de la gestión y almacenamiento de sangre y sus derivados.', 'Hematología', NEWID(), 1),
('Cardiología', 'Especialidad dedicada al estudio, diagnóstico y tratamiento de enfermedades del corazón.', 'Cardiología', NEWID(), 1),
('Centro de rehabilitacion', 'Especialidad enfocada en la recuperación funcional de pacientes con discapacidades físicas.', 'Rehabilitación', NEWID(), 1),
('Cirugia Bariatrica', 'Especialidad quirúrgica dedicada al tratamiento de la obesidad.', 'Cirugía', NEWID(), 1),
('Cirugia Cardiovascular', 'Especialidad que se ocupa de las intervenciones quirúrgicas del sistema cardiovascular.', 'Cirugía Cardiovascular', NEWID(), 1),
('Cirugia de seno y tejidos blandos', 'Especialidad quirúrgica centrada en el tratamiento del seno y tejidos blandos.', 'Cirugía', NEWID(), 1),
('Cirugia de toráx', 'Especialidad quirúrgica enfocada en el tratamiento de enfermedades del tórax.', 'Cirugía Torácica', NEWID(), 1),
('Cirugia Endoscópica', 'Especialidad quirúrgica que utiliza endoscopios para procedimientos menos invasivos.', 'Cirugía', NEWID(), 1),
('Cirugia Laparoscópica', 'Especialidad quirúrgica mínimamente invasiva que se realiza a través de pequeñas incisiones.', 'Cirugía Laparoscópica', NEWID(), 1),
('Cirugia maxilofacial', 'Especialidad quirúrgica dedicada al tratamiento de enfermedades y traumatismos del rostro y la boca.', 'Cirugía Maxilofacial', NEWID(), 1),
('Cirugia Plástica', 'Especialidad dedicada a la reconstrucción y mejora de la apariencia física.', 'Cirugía Plástica', NEWID(), 1),
('Cirugia vascular', 'Especialidad quirúrgica que trata enfermedades de los vasos sanguíneos.', 'Cirugía Vascular', NEWID(), 1),
('Dermatología', 'Especialidad que se ocupa del diagnóstico y tratamiento de enfermedades de la piel.', 'Dermatología', NEWID(), 1),
('Endocrinología', 'Especialidad médica que se dedica al estudio y tratamiento de las enfermedades hormonales.', 'Endocrinología', NEWID(), 1),
('Estomatología', 'Especialidad que se centra en el estudio y tratamiento de las enfermedades de la boca.', 'Estomatología', NEWID(), 1),
('Farmacología Clínica', 'Especialidad que estudia los efectos de los medicamentos en el cuerpo humano.', 'Farmacología Clínica', NEWID(), 1),
('Fisiatria', 'Especialidad dedicada a la rehabilitación física de pacientes con discapacidades.', 'Fisiatria', NEWID(), 1),
('Fisioterapia', 'Especialidad que se centra en la recuperación de la movilidad y función física.', 'Fisioterapia', NEWID(), 1),
('Fonoaudiología', 'Especialidad dedicada al tratamiento de trastornos del habla y la audición.', 'Fonoaudiología', NEWID(), 1),
('Gastroenterología', 'Especialidad que se dedica al estudio y tratamiento de enfermedades del sistema digestivo.', 'Gastroenterología', NEWID(), 1),
('Genética', 'Especialidad que estudia la herencia y las enfermedades genéticas.', 'Genética', NEWID(), 1),
('Geriatría', 'Especialidad que se enfoca en el cuidado y tratamiento de personas mayores.', 'Geriatría', NEWID(), 1),
('Gineco obstetricia', 'Especialidad médica que combina la ginecología y la obstetricia para el cuidado de la salud femenina.', 'Gineco obstetricia', NEWID(), 1),
('Ginecología', 'Especialidad médica que se ocupa de la salud del sistema reproductor femenino.', 'Ginecología', NEWID(), 1),
('Hematología y hemoterapia', 'Especialidad que estudia las enfermedades de la sangre y su tratamiento mediante transfusiones.', 'Hematología', NEWID(), 1),
('Hepatología', 'Especialidad que se dedica al estudio y tratamiento de las enfermedades del hígado.', 'Hepatología', NEWID(), 1),
('Infectología', 'Especialidad que se enfoca en el estudio y tratamiento de enfermedades infecciosas.', 'Infectología', NEWID(), 1),
('Inmunología', 'Especialidad que estudia el sistema inmunológico y sus trastornos.', 'Inmunología', NEWID(), 1),
('Laboratorio clínico', 'Especialidad dedicada al análisis de muestras biológicas para el diagnóstico médico.', 'Laboratorio clínico', NEWID(), 1),
('Laboratorio Farmaceutico', 'Especialidad que se encarga de la investigación y desarrollo de medicamentos.', 'Farmacología', NEWID(), 1),
('Mastología', 'Especialidad dedicada al estudio y tratamiento de las enfermedades mamarias.', 'Mastología', NEWID(), 1),
('Medicina aeroespacial', 'Especialidad médica que se ocupa de la salud de los astronautas y la medicina en condiciones espaciales.', 'Medicina Aeroespacial', NEWID(), 1),
('Medicina Alternativa', 'Especialidad que se centra en tratamientos no convencionales y holísticos.', 'Medicina Alternativa', NEWID(), 1),
('Medicina de la educación física y del deporte', 'Especialidad que estudia el impacto del deporte y la actividad física en la salud.', 'Medicina Deportiva', NEWID(), 1),
('Medicina del trabajo', 'Especialidad que se enfoca en la salud y seguridad en el lugar de trabajo.', 'Medicina del Trabajo', NEWID(), 1),
('Medicina Estetica', 'Especialidad dedicada a mejorar la apariencia física mediante tratamientos médicos.', 'Medicina Estética', NEWID(), 1),
('Medicina familiar y comunitaria', 'Especialidad médica que ofrece atención primaria integral para personas de todas las edades.', 'Medicina Familiar', NEWID(), 1),
('Medicina forense', 'Especialidad que aplica conocimientos médicos para la resolución de casos legales.', 'Medicina Forense', NEWID(), 1),
('Medicina general', 'Especialidad dedicada a la atención primaria y la prevención, diagnóstico y tratamiento de enfermedades comunes.', 'Medicina General', NEWID(), 1),
('Medicina intensiva', 'Especialidad que se centra en el cuidado de pacientes críticamente enfermos.', 'Medicina Intensiva', NEWID(), 1),
('Medicina interna', 'Especialidad médica dedicada al diagnóstico y tratamiento de enfermedades en adultos.', 'Medicina Interna', NEWID(), 1),
('Medicina legal y forense', 'Especialidad que combina medicina y derecho para investigar muertes sospechosas.', 'Medicina Forense', NEWID(), 1),
('Medicina Nuclear', 'Especialidad que utiliza isótopos radiactivos para el diagnóstico y tratamiento de enfermedades.', 'Medicina Nuclear', NEWID(), 1),
('Medicina preventiva y salud pública', 'Especialidad que se enfoca en la prevención de enfermedades y la promoción de la salud.', 'Medicina Preventiva', NEWID(), 1),
('Medicina Sexual', 'Especialidad médica dedicada al estudio y tratamiento de los trastornos sexuales.', 'Medicina Sexual', NEWID(), 1),
('Nefrología', 'Especialidad que estudia y trata enfermedades del riñón.', 'Nefrología', NEWID(), 1),
('Neumología', 'Especialidad médica que se centra en el diagnóstico y tratamiento de enfermedades pulmonares.', 'Neumología', NEWID(), 1),
('Neurocirugia', 'Especialidad quirúrgica que trata enfermedades del sistema nervioso.', 'Neurocirugía', NEWID(), 1),
('Neurofisiología Clínica', 'Especialidad que estudia las funciones del sistema nervioso mediante pruebas diagnósticas.', 'Neurofisiología', NEWID(), 1),
('Neurología', 'Especialidad médica que se ocupa del diagnóstico y tratamiento de enfermedades del sistema nervioso.', 'Neurología', NEWID(), 1),
('Nutricionista', 'Especialidad que se centra en la alimentación y nutrición para la promoción de la salud.', 'Nutrición', NEWID(), 1),
('Nutriología', 'Especialidad que estudia los procesos metabólicos y su relación con la salud.', 'Nutriología', NEWID(), 1),
('Obstetricia', 'Especialidad médica que se ocupa del embarazo, parto y puerperio.', 'Obstetricia', NEWID(), 1),
('Odontología', 'Especialidad que se ocupa del diagnóstico y tratamiento de enfermedades dentales.', 'Odontología', NEWID(), 1),
('Oftalmología', 'Especialidad médica que se enfoca en el diagnóstico y tratamiento de enfermedades oculares.', 'Oftalmología', NEWID(), 1),
('Oncología médica', 'Especialidad dedicada al estudio y tratamiento del cáncer.', 'Oncología', NEWID(), 1),
('Oncología radioterápica', 'Especialidad que utiliza la radiación para el tratamiento del cáncer.', 'Oncología', NEWID(), 1),
('Ortopedista', 'Especialidad médica que se ocupa del tratamiento de enfermedades del sistema musculoesquelético.', 'Ortopedia', NEWID(), 1),
('Otorrinolaringología', 'Especialidad médica que trata enfermedades del oído, nariz y garganta.', 'Otorrinolaringología', NEWID(), 1),
('Pediatría', 'Especialidad médica que se centra en el cuidado de la salud infantil.', 'Pediatría', NEWID(), 1),
('Podología', 'Especialidad que se enfoca en el diagnóstico y tratamiento de enfermedades del pie.', 'Podología', NEWID(), 1),
('Proctología', 'Especialidad que estudia y trata enfermedades del recto y el ano.', 'Proctología', NEWID(), 1),
('Psicología', 'Especialidad que se ocupa del estudio del comportamiento humano y su tratamiento.', 'Psicología', NEWID(), 1),
('Psiquiatría', 'Especialidad médica que se enfoca en el diagnóstico y tratamiento de enfermedades mentales.', 'Psiquiatría', NEWID(), 1),
('Quiropráctico', 'Especialidad que se enfoca en el tratamiento de trastornos del sistema musculoesquelético, especialmente la columna vertebral.', 'Quiropráctica', NEWID(), 1),
('Radiología', 'Especialidad que utiliza imágenes médicas para el diagnóstico y tratamiento de enfermedades.', 'Radiología', NEWID(), 1),
('Rehabilitación', 'Especialidad que se dedica a la recuperación funcional de personas con discapacidades físicas.', 'Rehabilitación', NEWID(), 1),
('Reumatología', 'Especialidad médica que se ocupa del diagnóstico y tratamiento de enfermedades reumáticas.', 'Reumatología', NEWID(), 1),
('Salud Ocupacional', 'Especialidad que se enfoca en la prevención de enfermedades y accidentes laborales.', 'Salud Ocupacional', NEWID(), 1),
('Toxicología', 'Especialidad que estudia los efectos nocivos de sustancias químicas en los seres humanos.', 'Toxicología', NEWID(), 1),
('Transplante de órganos', 'Especialidad médica dedicada al trasplante de órganos y tejidos.', 'Transplante', NEWID(), 1);


	--paises--
	INSERT INTO pais (nombre_pais, iso_pais, codigo_pais, gentilicio_pais, estado_pais)
VALUES 
    ('Afganistán', 'AFG', '+93', 'Afgano', 1),
    ('Albania', 'ALB', '+355', 'Albanés', 1),
    ('Alemania', 'DEU', '+49', 'Alemán', 1),
    ('Andorra', 'AND', '+376', 'Andorrano', 1),
    ('Angola', 'AGO', '+244', 'Angoleño', 1),
    ('Antigua y Barbuda', 'ATG', '+1268', 'Antiguano', 1),
    ('Arabia Saudita', 'SAU', '+966', 'Saudí', 1),
    ('Argelia', 'DZA', '+213', 'Argelino', 1),
    ('Argentina', 'ARG', '+54', 'Argentino', 1),
    ('Armenia', 'ARM', '+374', 'Armenio', 1),
    ('Australia', 'AUS', '+61', 'Australiano', 1),
    ('Austria', 'AUT', '+43', 'Austriaco', 1),
    ('Azerbaiyán', 'AZE', '+994', 'Azerbaiyano', 1),
    ('Bahamas', 'BHS', '+1242', 'Bahameño', 1),
    ('Bangladés', 'BGD', '+880', 'Bangladesí', 1),
    ('Barbados', 'BRB', '+1246', 'Barbadense', 1),
    ('Baréin', 'BHR', '+973', 'Bareiní', 1),
    ('Bélgica', 'BEL', '+32', 'Belga', 1),
    ('Belice', 'BLZ', '+501', 'Beliceño', 1),
    ('Benín', 'BEN', '+229', 'Beninés', 1),
    ('Bielorrusia', 'BLR', '+375', 'Bielorruso', 1),
    ('Birmania', 'MMR', '+95', 'Birmano', 1),
    ('Bolivia', 'BOL', '+591', 'Boliviano', 1),
    ('Bosnia y Herzegovina', 'BIH', '+387', 'Bosnio', 1),
    ('Botsuana', 'BWA', '+267', 'Botsuano', 1),
    ('Brasil', 'BRA', '+55', 'Brasileño', 1),
    ('Brunéi', 'BRN', '+673', 'Bruneano', 1),
    ('Bulgaria', 'BGR', '+359', 'Búlgaro', 1),
    ('Burkina Faso', 'BFA', '+226', 'Burkinés', 1),
    ('Burundi', 'BDI', '+257', 'Burundés', 1),
    ('Bután', 'BTN', '+975', 'Butanés', 1),
    ('Cabo Verde', 'CPV', '+238', 'Cabo-verdiano', 1),
    ('Camboya', 'KHM', '+855', 'Camboyano', 1),
    ('Camerún', 'CMR', '+237', 'Camerunés', 1),
    ('Canadá', 'CAN', '+1', 'Canadiense', 1),
    ('Catar', 'QAT', '+974', 'Catarí', 1),
    ('Chad', 'TCD', '+235', 'Chadiano', 1),
    ('Chile', 'CHL', '+56', 'Chileno', 1),
    ('China', 'CHN', '+86', 'Chino', 1),
    ('Chipre', 'CYP', '+357', 'Chipriota', 1),
    ('Colombia', 'COL', '+57', 'Colombiano', 1),
    ('Comoras', 'COM', '+269', 'Comorense', 1),
    ('Corea del Norte', 'PRK', '+850', 'Norcoreano', 1),
    ('Corea del Sur', 'KOR', '+82', 'Surcoreano', 1),
    ('Costa de Marfil', 'CIV', '+225', 'Marfileño', 1),
    ('Costa Rica', 'CRI', '+506', 'Costarricense', 1),
    ('Croacia', 'HRV', '+385', 'Croata', 1),
    ('Cuba', 'CUB', '+53', 'Cubano', 1),
    ('Dinamarca', 'DNK', '+45', 'Danés', 1),
    ('Dominica', 'DMA', '+1767', 'Dominiqués', 1),
    ('Ecuador', 'ECU', '+593', 'Ecuatoriano', 1),
    ('Egipto', 'EGY', '+20', 'Egipcio', 1),
    ('El Salvador', 'SLV', '+503', 'Salvadoreño', 1),
    ('Emiratos Árabes Unidos', 'ARE', '+971', 'Emiratí', 1),
    ('Eritrea', 'ERI', '+291', 'Eritreo', 1),
    ('Eslovaquia', 'SVK', '+421', 'Eslovaco', 1),
    ('Eslovenia', 'SVN', '+386', 'Esloveno', 1),
    ('España', 'ESP', '+34', 'Español', 1),
    ('Estados Unidos', 'USA', '+1', 'Estadounidense', 1),
    ('Estonia', 'EST', '+372', 'Estonio', 1),
    ('Esuatini', 'SWZ', '+268', 'Suazi', 1),
    ('Etiopía', 'ETH', '+251', 'Etíope', 1),
    ('Filipinas', 'PHL', '+63', 'Filipino', 1),
    ('Finlandia', 'FIN', '+358', 'Finlandés', 1),
    ('Fiyi', 'FJI', '+679', 'Fiyiano', 1),
    ('Francia', 'FRA', '+33', 'Francés', 1),
    ('Gabón', 'GAB', '+241', 'Gabonés', 1),
    ('Gambia', 'GMB', '+220', 'Gambiano', 1),
    ('Georgia', 'GEO', '+995', 'Georgiano', 1),
    ('Ghana', 'GHA', '+233', 'Ghanés', 1),
    ('Granada', 'GRD', '+1473', 'Granadino', 1),
    ('Grecia', 'GRC', '+30', 'Griego', 1),
    ('Guatemala', 'GTM', '+502', 'Guatemalteco', 1),
    ('Guinea', 'GIN', '+224', 'Guineano', 1),
    ('Guinea-Bisáu', 'GNB', '+245', 'Guineano', 1),
    ('Guinea Ecuatorial', 'GNQ', '+240', 'Ecuatoguineano', 1),
    ('Guyana', 'GUY', '+592', 'Guyanés', 1),
    ('Haití', 'HTI', '+509', 'Haitiano', 1),
    ('Honduras', 'HND', '+504', 'Hondureño', 1),
    ('Hungría', 'HUN', '+36', 'Húngaro', 1),
    ('India', 'IND', '+91', 'Indio', 1),
    ('Indonesia', 'IDN', '+62', 'Indonesio', 1),
    ('Irak', 'IRQ', '+964', 'Iraquí', 1),
    ('Irán', 'IRN', '+98', 'Iraní', 1),
    ('Irlanda', 'IRL', '+353', 'Irlandés', 1),
    ('Islandia', 'ISL', '+354', 'Islandés', 1),
    ('Islas Marshall', 'MHL', '+692', 'Marshalés', 1),
    ('Islas Salomón', 'SLB', '+677', 'Salomonense', 1),
    ('Israel', 'ISR', '+972', 'Israelí', 1),
    ('Italia', 'ITA', '+39', 'Italiano', 1),
    ('Jamaica', 'JAM', '+1876', 'Jamaicano', 1),
    ('Japón', 'JPN', '+81', 'Japonés', 1),
    ('Jordania', 'JOR', '+962', 'Jordano', 1),
    ('Kazajistán', 'KAZ', '+7', 'Kazajo', 1),
    ('Kenia', 'KEN', '+254', 'Keniano', 1),
    ('Kirguistán', 'KGZ', '+996', 'Kirguís', 1),
    ('Kiribati', 'KIR', '+686', 'Kiribatiano', 1),
    ('Kuwait', 'KWT', '+965', 'Kuwaití', 1),
    ('Laos', 'LAO', '+856', 'Laosiano', 1),
    ('Lesoto', 'LSO', '+266', 'Lesotense', 1),
    ('Letonia', 'LVA', '+371', 'Letón', 1),
    ('Líbano', 'LBN', '+961', 'Libanés', 1),
    ('Liberia', 'LBR', '+231', 'Liberiano', 1),
    ('Libia', 'LBY', '+218', 'Libio', 1),
    ('Liechtenstein', 'LIE', '+423', 'Liechtensteiniano', 1),
    ('Lituania', 'LTU', '+370', 'Lituano', 1),
    ('Luxemburgo', 'LUX', '+352', 'Luxemburgués', 1),
    ('Madagascar', 'MDG', '+261', 'Malgache', 1),
    ('Malasia', 'MYS', '+60', 'Malasio', 1),
    ('Malaui', 'MWI', '+265', 'Malauí', 1),
    ('Maldivas', 'MDV', '+960', 'Maldivo', 1),
    ('Malí', 'MLI', '+223', 'Maliense', 1),
    ('Malta', 'MLT', '+356', 'Maltés', 1),
    ('Marruecos', 'MAR', '+212', 'Marroquí', 1),
    ('Mauricio', 'MUS', '+230', 'Mauriciano', 1),
    ('Mauritania', 'MRT', '+222', 'Mauritano', 1),
    ('México', 'MEX', '+52', 'Mexicano', 1),
    ('Micronesia', 'FSM', '+691', 'Micronesio', 1),
    ('Moldavia', 'MDA', '+373', 'Moldavo', 1),
    ('Mónaco', 'MCO', '+377', 'Monegasco', 1),
    ('Mongolia', 'MNG', '+976', 'Mongol', 1),
    ('Montenegro', 'MNE', '+382', 'Montenegrino', 1),
    ('Mozambique', 'MOZ', '+258', 'Mozambiqueño', 1),
    ('Namibia', 'NAM', '+264', 'Namibio', 1),
    ('Nauru', 'NRU', '+674', 'Nauruano', 1),
    ('Nepal', 'NPL', '+977', 'Nepalí', 1),
    ('Nicaragua', 'NIC', '+505', 'Nicaragüense', 1),
    ('Níger', 'NER', '+227', 'Nigerino', 1),
    ('Nigeria', 'NGA', '+234', 'Nigeriano', 1),
    ('Noruega', 'NOR', '+47', 'Noruego', 1),
    ('Nueva Zelanda', 'NZL', '+64', 'Neozelandés', 1),
    ('Omán', 'OMN', '+968', 'Omaní', 1),
    ('Países Bajos', 'NLD', '+31', 'Neerlandés', 1),
    ('Pakistán', 'PAK', '+92', 'Pakistaní', 1),
    ('Palaos', 'PLW', '+680', 'Palauano', 1),
    ('Panamá', 'PAN', '+507', 'Panameño', 1),
    ('Papúa Nueva Guinea', 'PNG', '+675', 'Papú', 1),
    ('Paraguay', 'PRY', '+595', 'Paraguayo', 1),
    ('Perú', 'PER', '+51', 'Peruano', 1),
    ('Polonia', 'POL', '+48', 'Polaco', 1),
    ('Portugal', 'PRT', '+351', 'Portugués', 1),
    ('Reino Unido', 'GBR', '+44', 'Británico', 1),
    ('República Centroafricana', 'CAF', '+236', 'Centroafricano', 1),
    ('República Checa', 'CZE', '+420', 'Checo', 1),
    ('República Democrática del Congo', 'COD', '+243', 'Congoleño', 1),
    ('República Dominicana', 'DOM', '+1809', 'Dominicano', 1),
    ('República del Congo', 'COG', '+242', 'Congoleño', 1),
    ('Ruanda', 'RWA', '+250', 'Ruandés', 1),
    ('Rumanía', 'ROU', '+40', 'Rumano', 1),
    ('Rusia', 'RUS', '+7', 'Ruso', 1),
    ('Samoa', 'WSM', '+685', 'Samoano', 1),
    ('San Cristóbal y Nieves', 'KNA', '+1869', 'Sancristobaleño', 1),
    ('San Marino', 'SMR', '+378', 'Sanmarinense', 1),
    ('Santa Lucía', 'LCA', '+1758', 'Santalucense', 1),
    ('Santo Tomé y Príncipe', 'STP', '+239', 'Santotomense', 1),
    ('Senegal', 'SEN', '+221', 'Senegalés', 1),
    ('Serbia', 'SRB', '+381', 'Serbio', 1),
    ('Seychelles', 'SYC', '+248', 'Seychellense', 1),
    ('Sierra Leona', 'SLE', '+232', 'Sierraleonés', 1),
    ('Singapur', 'SGP', '+65', 'Singapurense', 1),
    ('Siria', 'SYR', '+963', 'Sirio', 1),
    ('Somalia', 'SOM', '+252', 'Somalí', 1),
    ('Sri Lanka', 'LKA', '+94', 'Ceilanés', 1),
    ('Sudáfrica', 'ZAF', '+27', 'Sudafricano', 1),
    ('Sudán', 'SDN', '+249', 'Sudanés', 1),
    ('Sudán del Sur', 'SSD', '+211', 'Sur-sudanés', 1),
    ('Suecia', 'SWE', '+46', 'Sueco', 1),
    ('Suiza', 'CHE', '+41', 'Suizo', 1),
    ('Surinam', 'SUR', '+597', 'Surinamés', 1),
    ('Tailandia', 'THA', '+66', 'Tailandés', 1),
    ('Tanzania', 'TZA', '+255', 'Tanzano', 1),
    ('Tayikistán', 'TJK', '+992', 'Tayiko', 1),
    ('Timor Oriental', 'TLS', '+670', 'Timorense', 1),
    ('Togo', 'TGO', '+228', 'Togolés', 1),
    ('Tonga', 'TON', '+676', 'Tongano', 1),
    ('Trinidad y Tobago', 'TTO', '+1868', 'Trinitense', 1),
    ('Túnez', 'TUN', '+216', 'Tunecino', 1),
    ('Turkmenistán', 'TKM', '+993', 'Turcomano', 1),
    ('Turquía', 'TUR', '+90', 'Turco', 1),
    ('Tuvalu', 'TUV', '+688', 'Tuvaluano', 1),
    ('Ucrania', 'UKR', '+380', 'Ucraniano', 1),
    ('Uganda', 'UGA', '+256', 'Ugandés', 1),
    ('Uruguay', 'URY', '+598', 'Uruguayo', 1),
    ('Uzbekistán', 'UZB', '+998', 'Uzbeko', 1),
    ('Vanuatu', 'VUT', '+678', 'Vanuatuense', 1),
    ('Venezuela', 'VEN', '+58', 'Venezolano', 1),
    ('Vietnam', 'VNM', '+84', 'Vietnamita', 1),
    ('Yemen', 'YEM', '+967', 'Yemení', 1),
    ('Yibuti', 'DJI', '+253', 'Yibutiano', 1),
    ('Zambia', 'ZMB', '+260', 'Zambiano', 1),
    ('Zimbabue', 'ZWE', '+263', 'Zimbabuense', 1);

	--LOCALIDAD--

	INSERT INTO localidad (
    fechacreacion_localidad, usuariocreacion_localidad, fechamodificacion_localidad, usuariomodificacion_localidad, nombre_localidad, gentilicio_localidad, prefijo_localidad, codigo_localidad,iso_localidad, isoad_localidad, cia_localidad, estado_localidad,pais_id
) VALUES
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Pichincha / Quito / Centro Histórico', 'Quiteño', '+593', 'UIO', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Pichincha / Quito / La Mariscal', 'Quiteño', '+593', 'UIO', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Pichincha / Rumiñahui / Sangolquí', 'Sangolquileño', '+593', 'RUM', 'EC', 'ECU', 'EC', 1, 51),
    
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Guayas / Guayaquil / Tarqui', 'Guayaquileño', '+593', 'GYE', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Guayas / Guayaquil / Ximena', 'Guayaquileño', '+593', 'GYE', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Guayas / Daule / La Aurora', 'Dauleño', '+593', 'DAU', 'EC', 'ECU', 'EC', 1, 51),

    (GETDATE(), 'admin', GETDATE(), 'admin', 'Azuay / Cuenca / Gil Ramírez Dávalos', 'Cuencano', '+593', 'CUE', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Azuay / Cuenca / Hermano Miguel', 'Cuencano', '+593', 'CUE', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Azuay / Gualaceo / Gualaceo', 'Gualaceño', '+593', 'GUA', 'EC', 'ECU', 'EC', 1, 51),

    (GETDATE(), 'admin', GETDATE(), 'admin', 'Manabí / Portoviejo / San Pablo', 'Portovejense', '+593', 'PVO', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Manabí / Manta / Tarqui', 'Manteño', '+593', 'MAN', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Manabí / Chone / Chone', 'Chonense', '+593', 'CHO', 'EC', 'ECU', 'EC', 1, 51),

    (GETDATE(), 'admin', GETDATE(), 'admin', 'Loja / Loja / El Sagrario', 'Lojano', '+593', 'LOJ', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Loja / Loja / San Sebastián', 'Lojano', '+593', 'LOJ', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Loja / Catamayo / Catamayo', 'Catamayense', '+593', 'CAT', 'EC', 'ECU', 'EC', 1, 51),

    (GETDATE(), 'admin', GETDATE(), 'admin', 'Tungurahua / Ambato / Atahualpa', 'Ambateño', '+593', 'AMB', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Tungurahua / Ambato / Celiano Monge', 'Ambateño', '+593', 'AMB', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Tungurahua / Baños de Agua Santa / Baños', 'Bañense', '+593', 'BAN', 'EC', 'ECU', 'EC', 1, 51),

    (GETDATE(), 'admin', GETDATE(), 'admin', 'Imbabura / Ibarra / Sagrario', 'Ibarreno', '+593', 'IBR', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Imbabura / Otavalo / Otavalo', 'Otavaleño', '+593', 'OTA', 'EC', 'ECU', 'EC', 1, 51),
    (GETDATE(), 'admin', GETDATE(), 'admin', 'Imbabura / Cotacachi / Cotacachi', 'Cotacacheño', '+593', 'COT', 'EC', 'ECU', 'EC', 1, 51);

	--usuario--
	INSERT INTO usuario (ci_usuario, nombres_usuario, apellidos_usuario, telefono_usuario, email_usuario, direccion_usuario, firmadigital_usuario, codigoqr_usuario, codigo_senecyt, login_usuario, clave_usuario, codigo_usuario, estado_usuario, perfil_id, establecimiento_id, especialidad_id)
VALUES 
(
    1234567890, 'Administrador','Admin','+593987654321','juan.perez@ejemplo.com','Av. Principal #123, Quito, Pichincha', NULL, NULL, 'MED123456','admin', 'admin', 'USR001', 1, 1, 1, 1  
);

SELECT id_pais FROM pais where nombre_pais = 'Ecuador'

--INSERT CATALOGO--
INSERT INTO catalogo ( fechacreacion_catalogo, usuariocreacion_catalogo, fechamodificacion_catalogo, usuariomodificacion_catalogo, descripcion_catalogo, categoria_catalogo, uuid_catalogo, estado_catalogo)
VALUES 



(GetDate(), 'Admin', NULL, NULL, 'FEMENINO', 'GENERO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MASCULINO', 'GENERO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'OTRO', 'GENERO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NO DEFINIDO', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'A+', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'A-', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'B+', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'B-', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'AB+', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'AB-', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'O+', 'TIPO DE SANGRE', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'O-', 'TIPO DE SANGRE', NEWID(), 1),

(GetDate(), 'Admin', NULL, NULL, 'CEDULA', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RUC', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PASAPORTE', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ADULTO SIN IDENTIFICAR', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MENOR SIN IDENTIFICAR', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CARNET DE REFUGIADO', 'TIPO DOCUMENTO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SOLTERO', 'ESTADO CIVIL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CASADO', 'ESTADO CIVIL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'UNION LIBRE', 'ESTADO CIVIL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DIVORCIADO', 'ESTADO CIVIL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'VIUDO', 'ESTADO CIVIL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SIN INSTRUCCIÓN', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PREESCOLAR', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PRIMARIA', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SECUNDARIA', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TECNICO', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TECNÓLOGO', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PROFESIONAL', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'POSGRADO', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MASTERADO', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DOCTORADO', 'FORMACION PROFESIONAL', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SIN SEGURO', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SEGURO PRIVADO', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'IEES', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ISSFA', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ISSPOL', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MSP', 'SEGUROS DE SALUD', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NINGUNO', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'AMIGO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PADRE', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MADRE', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HERMANO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TIO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PRIMO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ABUELO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PROMETIDO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NOVIO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESPOSO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HIJO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'COLEGA', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NIETO(A)', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'OTRO', 'PARENTESCO', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BISABUELO PATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BISABUELO MATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BISABUELA PATERNA', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BISABUELA MATERNA', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ABUELO PATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ABUELO MATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ABUELA PATERNA', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ABUELA MATERNA', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HERMANO(A)', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PADRE', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MADRE', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HIJO(A)', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TIO(A) PATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TIO(A) MATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PRIMO(A) PATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PRIMO(A) MATERNO', 'ANTECEDENTES FAMILIARES', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NINGUNA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CEREALES CON GLUTEN', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CRUSTÁCEOS Y PRODUCTOS A BASE DE CRUSTÁCEOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HUEVOS Y PRODUCTOS DERIVADOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PESCADO Y PRODUCTOS A BASE DE PESCADOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MANÍ, PRODUCTOS A BASE DE MANÍ Y FRUTOS SECOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SOJA Y PRODUCTOS A BASE DE SOJA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'LECHE Y SUS DERIVADOS (INCLUIDA LA LACTOSA)', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'FRUTOS DE CÁSCARA Y PRODUCTOS DERIVADOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'APIO Y PRODUCTOS DERIVADOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MOSTAZA Y PRODUCTOS A BASE DE MOSTAZA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'GRANOS O SEMILLAS DE SÉSAMO Y PRODUCTOS A BASE DE SÉSAMO', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DIÓXIDO DE AZUFRE Y SULFITOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALTRAMUCES Y PRODUCTOS A BASE DE ALTRAMUCES', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MOLUSCOS Y CRUSTÁCEOS Y PRODUCTOS A BASE DE ESTOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ASMA ALÉRGICA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RINITIS ALÉRGICA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CONJUNTIVITIS ALÉRGICA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DERMATITIS ATÓPICA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DERMATITIS DE CONTACTO', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA AL LÁTEX', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA A LOS MEDICAMENTOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA A LAS PICADURAS DE INSECTOS', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ANAFILAXIA', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA AL POLÉN', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA A LOS ÁCAROS DEL POLVO', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ALERGIA A LAS ESPORAS DEL MOHO', 'ALERGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'NINGUNA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ADENOIDECTOMÍA', 'CIRUGIAS', NEWID(), 1)
(GetDate(), 'Admin', NULL, NULL, 'AMIGDALECTOMÍA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'AMNIOCENTESIS TRANSABDOMINAL O VÍA VAGINAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ARTROSCOPÍA DIAGNÓSTICA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ARTROSCOPÍA TERAPÉUTICA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'AURICULOPLASTIAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BARTHOLINO, GLÁNDULAS DE SKENE (ABSCESO)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA DE EPIDÍDIMO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA DE PENE', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA DE PRÓSTATA POR PUNCIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA DE TESTÍCULO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA DE VAGINA, PUNCIÓN DE VAGINA (DIAGNÓSTICA O EXPLORADORA, PUNCIÓN DE SACO DE DOUGLAS)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA GANGLIONAR', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA ÓSEA Y MUSCULAR', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIA RENAL POR PUNCIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BIOPSIAS ORALES', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BLEFAROPLASTIA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'BRONCOSCOPÍAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CAMBIO DE NEFROSTOMÍA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CATARATAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CAUTERIZACIÓN DE LESIÓN HPV', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CELIOSCOPÍA, CULDOSCOPÍA O LAPAROSCOPÍA CONVENCIONAL CON', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE CÁMARA POSTERIOR', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE FISURA LABIO ALVEOLO PALATINA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE HALLUS VALGUS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE HERNIAS (INGUINALES,CRURALES, UMBILICALES)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE LA CÁMARA ANTERIOR', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE LAS GLÁNDULAS SALIVARES', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE LOS SENOS PARANASALES ENDOLUMINAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DE PÁRPADOS Y CONJUNTIVA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DEL CONDUCTO LAGRIMAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DEL OÍDO EXTERNO Y MEDIO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA DENTARIA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA MÍNIMAMENTE INVASORA PARA INCONTINENCIA DE ORINA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA QUISTE PILONIDAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍA VENOSA PERIFÉRICA (SAFENECTOMÍA, FLEBOEXTRACCIÓN, RESECCIONES ESCALONADAS)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CIRUGÍAS DEL TCS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CISTOSTOMÍA POR PUNCIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'COLGAJOS POR DESLIZAMIENTO Y ROTACIÓN (MENORES)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'COLPORRAFIA POR HERIDA, DESGARRO (FUERA DEL PARTO)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'COLPOTOMÍA, VAGINOTOMÍA DE DRENAJE (ABSCESO PELVIANO ESCISIÓN LOCAL DE LESIÓN VAGINAL)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CONIZACIÓN DE CUELLO COMO ÚNICA PRÁCTICA CON LEEP', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'CRIO COAGULACIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DERMOABRASIÓN PROFUNDA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DRENAJE DE ABSCESO MAMARIO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'DRENAJE DE ABSCESO TESTICULAR', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ENDOMETRIAL PARA CITOLÓGIA EXFOLIATIVA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'EPISIORRAFIA, PERINEORRAFIA O EPISIOPERINEORRAFIA (FUERA DEL PARTO)', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN DE CUERDA DORSAL O VENTRAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN DE LABIOS MAYORES, LABIOS MENORES, DE GLÁNDULAS DE', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN DE LESIÓN DE MAMA O PEZÓN PARA BIOPSIA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN DE LESIÓN DE PENE', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN LOCAL DE LESIÓN DE CUELLO (PÓLIPO), ELECTROCOAGULACIÓN DE CUELLO O CAUTERIZACIÓN QUÍMICA, BIOPSIA DE CUELLO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESCISIÓN LOCAL DE LESIÓN DE MAMA (QUISTE, FIBROADENOMA O TEJIDO MAMARIO ABERRANTE) DE LESIÓN DE CONDUCTO DE PEZÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ESTRABISMO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'EXTRACCIÓN DE OSTEOSÍNTESIS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'FIBROENDOSCOPÍAS ALTAS Y/O BAJAS DIAGNOSTICAS Y/O TERAPÉUTICAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'HIDROTURACIÓN, BIOPSIA O DEBRIDACIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'IMPLANTES CAPILARES', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'INJERTOS DE PIEL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'INJERTOS DE PIEL INTERMEDIA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'LAPAROSCOPÍA CON CIRUGÍA ANEXIAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'LAPAROSCOPIA DIAGNOSTICA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'LIFTING COMPLETO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'LIPOASPIRACIÓN LOCALIZADA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MARCACIÓN MAMARIA PRE QUIRÚRGICA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MASTOPLASTÍA DE INCLUSIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MASTOPLASTÍA REDUCTORA Y PTOSIS PEQUEÑAS QUE NO REQUIERAN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MEATOTOMÍA URETRAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MINI DERMOLIPECTOMÍA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'MIRINGOPLASTÍA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ORQUIDOPEXIA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PATOLOGÍA ORIFICIAL ANAL: HEMORROIDES, TROMBOSIS HEMORROIDAL, FISTULAS ANALES, FISURA ANAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'POSTIOPLASTIA-CIRCUNCISIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PUNCIÓN DE DERRAME ESCROTAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PUNCIÓN EVACUADORA DE QUISTE RENAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PUNCIÓN EVACUADORA VESICAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'PUNCIÓN QUISTE MAMARIO, PUNCIÓN BIOPSIA DE MAMA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RASPADO UTERINO DIAGNÓSTICO CON O SIN BIOPSIA DE CUELLO O ASPIRACIÓN', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RASPADO UTERINO TERAPÉUTICO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RETIRO DE CATÉTER URETERAL', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'RINOPLASTIAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ROTACIÓN DE COLGAJOS MEDIANOS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SECCIÓN DE FRENILLO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'SHUNT A-V PARA HEMODIÁLISIS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TRANSFUSIÓN SANGUÍNEA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TRATAMIENTO DE QUEMADURAS DE HASTA UN 15% DE PROFUNDIDAD', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'TUMORES DE PIEL Y CELULAR SUBCUTÁNEO', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'VASECTOMÍA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'VIDEOENDOSCOPIAS ALTAS Y/O BAJAS DIAGNOSTICAS Y/O TERAPÉUTICAS', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'VIDEOHISTEROSCOPÍA DIAGNÓSTICA Y/O TERAPÉUTICA', 'CIRUGIAS', NEWID(), 1),
(GetDate(), 'Admin', NULL, NULL, 'ZETAPLASTÍAS', 'CIRUGIAS', NEWID(), 1);
-- Insertar registros en la tabla diagnostico
INSERT INTO diagnostico (nombre_diagnostico, descripcion_diagnostico, categoria_diagnostico, estado_diagnostico, codigo_diagnostico)
VALUES 
('Gripe', 'Infección viral que afecta el sistema respiratorio.', 'Enfermedades Infecciosas', 1, 'J10'),
('Diabetes mellitus tipo 2', 'Trastorno metabólico caracterizado por hiperglucemia crónica.', 'Enfermedades Endocrinas', 1, 'E11'),
('Hipertensión esencial', 'Presión arterial alta sin causa identificable.', 'Enfermedades del Sistema Circulatorio', 1, 'I10'),
('Asma', 'Enfermedad respiratoria crónica que causa dificultades para respirar.', 'Enfermedades Respiratorias', 1, 'J45'),
('Gastritis aguda', 'Inflamación del revestimiento del estómago.', 'Enfermedades del Sistema Digestivo', 1, 'K29.0'),
('Migraña', 'Cefalea recurrente que puede estar acompañada de síntomas neurológicos.', 'Enfermedades Neurológicas', 1, 'G43'),
('Depresión mayor', 'Trastorno mental que causa un estado de ánimo persistentemente triste o bajo.', 'Trastornos Mentales', 1, 'F32'),
('Osteoartritis', 'Desgaste del cartílago articular que provoca dolor y rigidez en las articulaciones.', 'Enfermedades del Sistema Musculoesquelético', 1, 'M15'),
('Neumonía', 'Infección del parénquima pulmonar.', 'Enfermedades Respiratorias', 1, 'J18'),
('Cistitis aguda', 'Inflamación de la vejiga generalmente causada por una infección.', 'Enfermedades del Sistema Urinario', 1, 'N30.0');

GO
-- Insertar registros en la tabla laboratorio con el código CIE-10 en el campo uuid_laboratorios
INSERT INTO laboratorio (nombre_laboratorio, descripcion_laboratorio, categoria_laboratorios, uuid_laboratorios, estado_laboratorios)
VALUES 
('Hematología', 'Laboratorio especializado en análisis de sangre y componentes sanguíneos.', 'Análisis Clínicos', 'D50', 1),
('Microbiología', 'Laboratorio dedicado a la identificación de microorganismos patógenos.', 'Análisis Clínicos', 'A09', 1),
('Bioquímica', 'Laboratorio que realiza análisis químicos en sangre, orina y otros fluidos.', 'Análisis Clínicos', 'E11', 1),
('Inmunología', 'Laboratorio enfocado en estudios del sistema inmunológico y anticuerpos.', 'Análisis Clínicos', 'D84', 1),
('Genética Molecular', 'Laboratorio especializado en análisis de material genético.', 'Análisis Especializados', 'Q90', 1),
('Toxicología', 'Laboratorio que detecta sustancias tóxicas en el cuerpo.', 'Análisis Clínicos', 'T50', 1),
('Patología', 'Laboratorio que analiza tejidos y células para diagnosticar enfermedades.', 'Análisis Especializados', 'C50', 1),
('Virología', 'Laboratorio especializado en el estudio de virus.', 'Análisis Clínicos', 'B25', 1),
('Parasitología', 'Laboratorio que detecta y estudia parásitos en muestras biológicas.', 'Análisis Clínicos', 'B65', 1),
('Hormonales', 'Laboratorio que mide los niveles de hormonas en el cuerpo.', 'Análisis Clínicos', 'E03', 1);

GO

-- Insertar registros en la tabla medicamentos con códigos CIE-10 en uuid_medicamento
INSERT INTO medicamentos (nombre_medicamento, descripcion_medicamento, categoria_medicamento, distintivo_medicamento, concentracion_medicamento, uuid_medicamento, estado_medicamento)
VALUES 
('Paracetamol', 'Analgésico y antipirético utilizado para tratar el dolor y la fiebre.', 'Analgésicos', 'TYLENOL', '500 mg', 'N02BE01', 1),
('Amoxicilina', 'Antibiótico utilizado para tratar una amplia variedad de infecciones bacterianas.', 'Antibióticos', 'AMOXIL', '500 mg', 'J01CA04', 1),
('Ibuprofeno', 'Antiinflamatorio no esteroideo utilizado para aliviar el dolor y la inflamación.', 'Antiinflamatorios', 'ADVIL', '400 mg', 'M01AE01', 1),
('Aspirina', 'Analgésico y antipirético también utilizado como anticoagulante.', 'Analgésicos', 'ASPIRIN', '100 mg', 'B01AC06', 1),
('Metformina', 'Medicamento utilizado en el tratamiento de la diabetes tipo 2.', 'Antidiabéticos', 'GLUCOPHAGE', '850 mg', 'A10BA02', 1),
('Loratadina', 'Antihistamínico utilizado para aliviar los síntomas de alergia.', 'Antihistamínicos', 'CLARITIN', '10 mg', 'R06AX13', 1),
('Omeprazol', 'Inhibidor de la bomba de protones utilizado para tratar el reflujo ácido.', 'Antiulcerosos', 'PRILOSEC', '20 mg', 'A02BC01', 1),
('Simvastatina', 'Medicamento utilizado para reducir los niveles de colesterol.', 'Hipolipemiantes', 'ZOCOR', '20 mg', 'C10AA01', 1),
('Ciprofloxacino', 'Antibiótico utilizado para tratar infecciones bacterianas graves.', 'Antibióticos', 'CIPRO', '500 mg', 'J01MA02', 1),
('Lisinopril', 'Inhibidor de la ECA utilizado para tratar la hipertensión.', 'Antihipertensivos', 'ZESTRIL', '10 mg', 'C09AA03', 1);

GO
-- Insertar registros en la tabla imagen con códigos CIE-10 en uuid_imagen
INSERT INTO imagen (nombre_imagen, descripcion_imagen, categoria_imagen, uuid_imagen, estado_imagen)
VALUES 
('Radiografía de Tórax', 'Imagen utilizada para diagnosticar enfermedades pulmonares.', 'Radiología', 'J18', 1),
('Tomografía Computarizada de Abdomen', 'Imagen detallada del abdomen utilizada para evaluar órganos internos.', 'Tomografía', 'K55', 1),
('Resonancia Magnética de Cerebro', 'Imagen detallada del cerebro utilizada para diagnosticar trastornos neurológicos.', 'Resonancia Magnética', 'G93', 1),
('Ecografía Obstétrica', 'Imagen utilizada para monitorear el desarrollo del feto durante el embarazo.', 'Ecografía', 'O36', 1),
('Mamografía', 'Imagen utilizada para la detección temprana de cáncer de mama.', 'Radiología', 'C50', 1),
('Radiografía de Mano', 'Imagen utilizada para evaluar fracturas y otros problemas óseos.', 'Radiología', 'S62', 1),
('Ecocardiograma', 'Imagen utilizada para evaluar la estructura y función del corazón.', 'Ecografía', 'I51', 1),
('Angiografía Coronaria', 'Imagen utilizada para visualizar las arterias coronarias.', 'Angiografía', 'I25', 1),
('PET Scan de Cuerpo Completo', 'Imagen utilizada para evaluar el metabolismo y la función de tejidos y órganos.', 'PET', 'C34', 1),
('Ultrasonido Abdominal', 'Imagen utilizada para evaluar el estado de los órganos abdominales.', 'Ecografía', 'K83', 1);

GO
